GET http://localhost:8080/neopo/api/xxx

###

POST http://localhost:8080/neopo/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion

{"str1": "test", "str2": "test"}

###
startcode
GET http://localhost:8080/neopo/api/xxx/2

###
PUT  http://localhost:8080/neopo/api/xxx/2
Content-Type: application/json

{"str1": "a", "str2": "b"}






###
POST http://localhost:8080/neopo/api/Person
Content-Type: application/json

{"firstName": "Nicolai", "lastName": "Olsen", "email": "olsen@hotmail.com"}

###

GET http://localhost:8080/neopo/api/Person/1

###
GET http://localhost:8080/neopo/api/Person/2






###
GET http://localhost:8080/neopo/api/Hobby/

###
GET http://localhost:8080/neopo/api/Hobby/all
###
POST http://localhost:8080/neopo/api/Hobby
Content-Type: application/json

{"name": "fodbold", "description": "spark til bold"}
