GET http://localhost:8080/neopo/api/xxx

###

POST http://localhost:8080/neopo/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion
{"str1": "test", "str2": "test"}

###

PUT  http://localhost:8080/neopo/api/xxx/2
Content-Type: application/json
{"str1": "a", "str2": "b"}






###
POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{"firstName": "kent", "lastName": "mortensen", "email": "kent@hotmail.com"}

###

GET http://localhost:8080/neopo/api/Person/1






###
POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "kent",
  "lastName": "mortensen",
  "email": "kent@hotmail.com",
  "phones": [
    {
      "number": "12321232",
      "description": "james tele"
    },{
      "number": "122321232",
      "description": "jame2s tele"
    }
  ]


}

### test 1
POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "jacob",
  "lastName": "borch",
  "email": "borchaboi@hotmail.com",
  "phones": [
    {
      "number": "23773212",
      "description": "jacob borchs telefon"
    }
  ]
}
### create person with hobbies

POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "jacob",
  "lastName": "borch",
  "email": "borchaboi@hotmail.com",
  "hobbies": [
    {
      "name": "mariocart",
      "description": "retro video game"
    }
  ],

  "phones": [
    {
      "number": "23773212",
      "description": "jacob borchs telefon"
    }
  ]
}
















### create personwith hobbies and phone and address

POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "jacob",
  "lastName": "borch",
  "email": "borchaboi@hotmail.com",
  "hobbies": [
    {
      "name": "mariocart",
      "description": "retro video game"
    }
  ],
  "phones": [
    {
      "number": "23773212",
      "description": "jacob borchs telefon"
    }
  ],

  "address": {
    "street": "gefionsparken",
    "info": "19 st.tv.",
    "city": {
      "id": 1
    }
  }


}

### create personwith hobbies and phone and address

POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "metthew",
  "lastName": "renodu",
  "email": "mizkif@hotmail.com",

  "phones": [
    {
      "number": "23773212",
      "description": "mizkif"
    }
  ],

  "address": {
    "street": "ggh",
    "info": "ggh",
    "city": {
      "id": 2
    }
  }


}

### create personwith hobbies and phone and address

POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "metthew",
  "lastName": "renodu",
  "email": "mizkif@hotmail.com",
  "hobbies": [
    {
      "id": 1,
      "name": "basketball",
      "desciption": "game"

    },
    {
      "id": 23,
      "name": "basketball",
      "desciption": "game"
    }

  ],
  "phones": [
    {
      "number": "23773212",
      "description": "mizkif"
    }
  ],
  "address": {
    "street": "ve",
    "info": "ve",
    "city": {
      "id": 3
    }
  }
}

###

GET http://localhost:8080/neopo/api/Person/2


###
POST http://localhost:8080/neopo/api/Hobby
Content-Type: application/json

{"name": "fodbold", "description": "spark til bold"}



###

GET http://localhost:8080/neopo/api/Person/getAll

###
GET http://localhost:8080/neopo/api/Person/getAllByHobby/1

###
GET http://localhost:8080/neopo/api/Person/persons/1

###
POST http://localhost:8080/neopo/api/Person/addhobby/1/12
