GET http://localhost:8080/neopo/api/xxx

###

POST http://localhost:8080/neopo/api/xxx
Content-Type: application/json
#User-Agent: Mozilla/5.0 (platform; rv:geckoversion) Gecko/geckotrail Firefox/firefoxversion
{"str1": "test", "str2": "test"}

###

PUT  http://localhost:8080/neopo/api/xxx/2
Content-Type: application/json
{"str1": "a", "str2": "b"}






###
POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{"firstName": "kent", "lastName": "mortensen", "email": "kent@hotmail.com"}

###

GET http://localhost:8080/neopo/api/Person/1

###

GET http://localhost:8080/neopo/api/Person/2






###
POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "kent",
  "lastName": "mortensen",
  "email": "kent@hotmail.com",
  "phones": [
    {
      "number": "12321232",
      "description": "james tele"
    },{
      "number": "122321232",
      "description": "jame2s tele"
    }
  ]


}

### test 1
POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "jacob",
  "lastName": "borch",
  "email": "borchaboi@hotmail.com",
  "phones": [
    {
      "number": "23773212",
      "description": "jacob borchs telefon"
    }
  ]
}
### create person with hobbies

POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "jacob",
  "lastName": "borch",
  "email": "borchaboi@hotmail.com",
  "hobbies": [
    {
      "name": "mariocart",
      "description": "retro video game"
    }
  ],

  "phones": [
    {
      "number": "23773212",
      "description": "jacob borchs telefon"
    }
  ]
}
### create person with hobbies and phone and address

POST http://localhost:8080/neopo/api/Person/create
Content-Type: application/json

{
  "firstName": "jacob",
  "lastName": "borch",
  "email": "borchaboi@hotmail.com",
  "hobbies": [
    {
      "name": "mariocart",
      "description": "retro video game"
    }
  ],
  "phones": [
    {
      "number": "23773212",
      "description": "jacob borchs telefon"
    }
  ],

  "addressDTO": {
    "street": "gefionsparken",
    "info": "19 st.tv.",

    "cityDTO": {
      "zipcode": "3000",
      "name": "Helsingør"
    }
  }


}


###
GET http://localhost:8080/neopo/api/Hobby/

###
GET http://localhost:8080/neopo/api/Hobby/all
###
POST http://localhost:8080/neopo/api/Hobby
Content-Type: application/json

{"name": "fodbold", "description": "spark til bold"}
